version: "3.9"

services:
  fastapi:
    image: nitheesh86/mlops-frontend:bed3fc7
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"

  streamlit:
    image: nitheesh86/mlops-backend:bed3fc7
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      API_URL: http://fastapi:8000
